### ISSUE TITLE
both error & keepAliveTimeout are emitted

### ISSUE THREAD

**Issue by behrad** [mcollina/aedes#125]
Is this the desired behavior to emit both [here](https://github.com/mcollina/aedes/blob/master/lib/handlers/connect.js#L43-L44)?

I expected `clientError`, `clientDisconnect` and `keepAliveTimeout` to be exclusive events so that application can be easily decide on the client termination.

**Comment by mcollina** [comment]
Should it? If keepalive is triggered, I think we should terminate the client anyhow. Why would you prefer otherwise? Firing `'error'` makes the client disconnect abruptly.

A possibility is to fire `'keepAliveTimeout'`, and if there were no listeners to that event fire `'error'`. I'm not keen on this, as I would like to disconnect anyhow.

**Comment by behrad** [comment]
As far I translate to this:
`clientError` & `clientDisconnect` are mutually exclusive (i.e. only one of them would be emitted on a single client) However for certain cases we have duplicate events like `keepAliveTimeout`.

However application could handle that this way:
```
aedes.on('clientError', (client, err) => { 
  if (err.message === 'keepAliveTimeout') blah... 
})
```

Am I right?

**Comment by mcollina** [comment]
@behrad yes, I think so. You can't really "handle" those cases, but rather log them and use them for stats. There is not much you can do for those cases.

**Comment by behrad** [comment]
Thank you @mcollina ,
There's an issue I've seen testing aedes, where 
`client` param is null on `clientError` when `err=ECONNRESET`
and `packet` param is null on `ack` !!!
I checked aedes code, no suspects yet.
