### ISSUE TITLE
Bunyan support

### ISSUE THREAD

**Issue by behrad** [mcollina/aedes#26]
Bunyan log/stream support in Mosca was very helpful in my production system. Are you planning to also add it to Aedes @mcollina ? or alternative currently available inside?

**Comment by mcollina** [comment]
Aedes will not do any logging, it needs to come separately. Most of the relevant data should be already being published as events in the Aedes or Client objects, if not we'll need to add what is missing. If you are willing to help supporting that, just setup a repo and implement it :D. Otherwise I will get that done anyway (it will be bundled in Mosca) - after I finish MongoDB persistence.

**Comment by behrad** [comment]
Great @mcollina , 


> (it will be bundled in Mosca)

Are you planning to refactor Mosca on top of Aedes?

**Comment by mcollina** [comment]
That's the end goal.

**Comment by behrad** [comment]
For migration of my current app there are missing parts now: mosca-like JSON Authentication, HTTP port, Bunyan streams & stats.
