### ISSUE TITLE
Help with qos 2

### ISSUE THREAD

**Issue by guptaashishiitr** [mcollina/aedes#27]
I am trying to implement qos 2 and using aedes persistence lib for in memory persistence just for proof of concept that it works. Code below:

In one of the js files I call below: (aedesServer is instance aedesServer which is a separate configuration file)
```
aedesServer.publish(message, function (errm) { });
```
In message I am setting messageId 22 jst to test and found that 
```
aedes.on('publish', ...
```
always has messageId 0 .

Q1 -> Is messageId added and tracked by broker? If yes, then whey I keep getting messageId as 0 in on publish event?
Q2 -> Q1 is when I am publishing message to clients directly from broker. What if I publish directly from a connected client to broker? Should I add messageId then or broker takes care of it as well?
Q3 -> I published one message with messageId as 22 but no client was connected and subscribed to that topic at that point. After that I connected the client and subscribed to that topic. Shouldn't in memory persistence send that offline packet?

code for persistence 
```
var inmempersistence = require('aedes-persistence')()
var aedes = require('aedes')({
        persistence: inmempersistence
});
```

**Comment by mcollina** [comment]
Q1: regarding messgeId, it's 0 by design. Don't worry about it, and never specify it.
Q2: your MQTT client should take care of that, if not, you should do it by implementing the MQTT spec. MQTT.js does it for you.
Q3: no, check out how the "clean" flag works in the MQTT spec for QoS 1 and 2. Also read about the retain flag.
