### ISSUE TITLE
This and mosca, a little guidance...

### ISSUE THREAD

**Issue by cendrizzi** [mcollina/aedes#71]
This is not a real issue but a question for guidance. I've played with Mosca and everything worked well. I was curious about QOS 2, and then found this project as a result (it implements it where the Mosca did not, even though I don't need it). 

At the bottom of the readme for aedes it says "This addresses your concerns about performance and stability.". 

I was curious if this could be elaborated further. What issues are people finding? My feeling was that mosca was a fairly small layer running on top of redis or your backend of choice (which made me assume that is was very performant and ready for production as you can just launch more instances and as long as the backend can handle it then you are good, assuming you have a load balancer and stuff).

At this juncture, especially if using redis (which allows clusters and running on multi-cores for aedes if I'm understanding things), would aedes be the better project to use in a production environment over mosca? Especially if we have just been playing with mosca at this point?

**Comment by mcollina** [comment]
@cendrizzi Aedes is mosca++. It will be the same small layer, but faster, and easier to build and test. It's break down in lots of small modules that can be tested and released independently.

It is hard to contribute to Mosca. This project should lower that barrier as well.

Mosca has lots of internal quirks and if-then-else because of some poor choices of the internal data structures it is using. Those have been fixed in Aedes as well.

In the end, i will move Mosca on top of Aedes. Aedes is not ready yet.

**Comment by cendrizzi** [comment]
Thanks for the explanation!
